version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl
      - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client

  pre_build:
    commands:
      - echo Updating kubeconfig for EKS
      - aws eks update-kubeconfig --name brain-cluster --region ap-south-1

  build:
    commands:
      - echo Building Docker image
      - docker build -t shivark1996/brain-tasks-app:latest .
      - docker push shivark1996/brain-tasks-app:latest

  post_build:
    commands:
      - echo Deploying to EKS
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml
      - kubectl rollout status deployment/brain-app
      - kubectl get pods
      - kubectl get svc
