version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl

      # ✅ stable official Kubernetes download (FIX)
      - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"

      # safety check
      - ls -l kubectl
      - file kubectl

      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

      - kubectl version --client

  pre_build:
    commands:
      - echo Updating kubeconfig for EKS
      - aws eks update-kubeconfig --name brain-cluster --region ap-south-1

  build:
    commands:
      - echo Deploying application to EKS
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

  post_build:
    commands:
      - echo Deployment completed successfully
