version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl
      - curl -o kubectl https://s3.amazonaws.com/amazon-eks/1.29.0/2023-12-01/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Updating kubeconfig for EKS
      - aws eks update-kubeconfig --name brain-cluster --region ap-south-1

  build:
    commands:
      - echo Deploying application to EKS
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

  post_build:
    commands:
      - echo Deployment completed successfully
